/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "primary-container": "#8c1515",
                "tertiary-fixed-dim": "#c9c6c1",
                "surface-dim": "#dbd9d9",
                "outline-variant": "#e0bfbb",
                "on-surface": "#1b1c1c",
                "on-secondary-container": "#745c00",
                "secondary-fixed": "#ffe088",
                "tertiary": "#30302c",
                "primary-fixed-dim": "#ffb4ab",
                "background": "#fbf9f8",
                "primary-fixed": "#ffdad6",
                "surface-container-highest": "#e4e2e2",
                "secondary-container": "#fed65b",
                "on-surface-variant": "#59413e",
                "surface-container-high": "#eae8e7",
                "on-tertiary-container": "#b6b4af",
                "on-tertiary-fixed": "#1c1c18",
                "surface-variant": "#e4e2e2",
                "on-secondary-fixed-variant": "#574500",
                "on-error-container": "#93000a",
                "on-secondary-fixed": "#241a00",
                "secondary": "#735c00",
                "primary": "#680006",
                "on-primary-container": "#ff998e",
                "tertiary-container": "#474642",
                "surface-tint": "#ae2f2a",
                "on-secondary": "#ffffff",
                "inverse-surface": "#303030",
                "tertiary-fixed": "#e5e2dc",
                "on-primary": "#ffffff",
                "outline": "#8d706d",
                "surface-container-low": "#f5f3f3",
                "surface": "#fbf9f8",
                "on-tertiary-fixed-variant": "#474743",
                "inverse-primary": "#ffb4ab",
                "on-error": "#ffffff",
                "on-primary-fixed-variant": "#8d1515",
                "on-background": "#1b1c1c",
                "secondary-fixed-dim": "#e9c349",
                "on-tertiary": "#ffffff",
                "surface-container": "#efeded",
                "error-container": "#ffdad6",
                "error": "#ba1a1a",
                "surface-bright": "#fbf9f8",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed": "#410002",
                "inverse-on-surface": "#f2f0f0"
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            spacing: {
                "margin-mobile": "20px",
                "gutter": "24px",
                "margin-desktop": "40px",
                "unit": "8px",
                "container-max": "1440px"
            },
            fontFamily: {
                "sans": ["Be Vietnam Pro", "sans-serif"],
                "headline": ["Be Vietnam Pro", "sans-serif"],
                "body": ["Be Vietnam Pro", "sans-serif"],
            },
        },
    },
    plugins: [],
}
